language: clang

sudo: required
dist: trusty

branches:
  except:
    - release

branches:
  only:
    - master
    - develop

addons:
  apt:
    packages:
    - build-essential
    - cmake
    - gcc
    - lcov
    - devscripts
    - pbuilder
    - strace
    - lsof
    - gdb
    - valgrind
    - python
    - python-dev
    - python-pip
    - libffi-dev
    - doxygen
    - doxygen-latex
    - mingw-w64
    - binutils-mingw-w64
    - mingw-w64-tools
    - mingw-w64-i686-dev
    - mingw-w64-x86-64-dev

install:
  - pip install --user --upgrade pip
  - pip install --user cffi
  - export PATH=$PATH:$HOME/.local/bin

script:
  - echo -e "\n\n*** BUILD FOR COVERAGE ***\n"
  - mkdir -p target/build_test/coverage
  - cd target/build_test
  - cmake -D CMAKE_BUILD_TYPE=Coverage -D CMAKE_INSTALL_PREFIX=/opt/amcl -D WORD_LENGTH=64 -D USE_ANONYMOUS=on -D BUILD_WCC=on ../..
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./
  - make
  - lcov --zerocounters --directory .
  - lcov --capture --initial --directory . --output-file coverage/amcl
  - make test
  - lcov --no-checksum --directory . --capture --output-file coverage/amcl.info
  - genhtml -o coverage -t "milagro-crypto-c Test Coverage" coverage/amcl.info
  - make doc
  - echo -e "\n\n*** BUILD LINUX 64 ***\n\n"
  - mkdir -p target/build_linux64
  - cd target/build_linux64
  - cmake -D CMAKE_INSTALL_PREFIX=/opt/amcl -D WORD_LENGTH=64 ../..
  - make
  - make test
  - make package
  - echo -e "\n\n*** BUILD LINUX 32 ***\n\n"
  - mkdir -p target/build_linux32
  - cd target/build_linux32
  - cmake -D CMAKE_INSTALL_PREFIX=/opt/amcl -D WORD_LENGTH=32 ../..
  - make
  - make test
  - make package
  - echo -e "\n\n*** BUILD WIN 64 ***\n\n"
  - mkdir -p target/build_win64
  - cd target/build_win64
  - cmake -D CMAKE_TOOLCHAIN_FILE=../../resources/cmake/mingw64-cross.cmake -D WORD_LENGTH=64 ../..
  - make
  - echo -e "\n\n*** BUILD WIN 32 ***\n\n"
  - mkdir -p target/build_win32
  - cd target/build_win32
  - cmake -D CMAKE_TOOLCHAIN_FILE=../../resources/cmake/mingw32-cross.cmake -D WORD_LENGTH=32 ../..
  - make
