language: clang
sudo: required
dist: trusty
services:
  - docker

install:
  - gem install coveralls-lcov

script:
  - make -f Makefile.docker
  - make -f Makefile.docker buildall

after_success:
  - coveralls-lcov /home/travis/build/milagro-crypto/milagro-crypto-c/target/LINUX_64BIT_COVERAGE/coverage/amcl.info
