language: clang

sudo: required
dist: trusty

branches:
  except:
    - release

branches:
  only:
    - master
    - develop

before_install:
    # Enable i386 for wine
    - sudo dpkg --add-architecture i386
    - sudo apt-get update || true
    - sudo apt-get -y install wine
    - wine --version

addons:
  apt:
    packages:
    - build-essential
    - cmake
    - gcc
    - lcov
    - devscripts
    - pbuilder
    - strace
    - lsof
    - gdb
    - valgrind
    - python
    - python-dev
    - python-pip
    - libffi-dev
    - doxygen
    - doxygen-latex
    - mingw-w64
    - binutils-mingw-w64
    - mingw-w64-tools
    - mingw-w64-i686-dev
    - mingw-w64-x86-64-dev
    - golang

install:
  - pip install --user --upgrade pip
  - pip install --user cffi
  - mkdir -p /home/travis/build/bin && \
  - mkdir -p /home/travis/build/pkg && \
  - mkdir -p /home/travis/build/src && \
  - export GOPATH=/home/travis/build/
  - export PATH=$GOPATH/bin:$PATH:$HOME/.local/bin
  - gem install coveralls-lcov
  - go get github.com/stretchr/testify/assert

script:
  - echo -e "\n\n*** BUILD FOR COVERAGE ***\n"
  - mkdir -p /home/travis/build/miracl/milagro-crypto-c/target/build_test/coverage
  - cd /home/travis/build/miracl/milagro-crypto-c/target/build_test
  - cmake -D CMAKE_BUILD_TYPE=Coverage -D CMAKE_INSTALL_PREFIX=/opt/amcl -D WORD_LENGTH=64 -D BUILD_WCC=on ../..
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./
  - make
  - lcov --zerocounters --directory .
  - lcov --capture --initial --directory . --output-file coverage/amcl
  - env CTEST_OUTPUT_ON_FAILURE=1 make test
  - lcov --no-checksum --directory . --capture --output-file coverage/amcl.info
  - genhtml -o coverage -t "milagro-crypto-c Test Coverage" coverage/amcl.info
  - make doc
  - echo -e "\n\n*** BUILD LINUX 64 WRAPPERS ***\n\n"
  - mkdir -p /home/travis/build/miracl/milagro-crypto-c/target/build_linux64_wrappers
  - cd /home/travis/build/miracl/milagro-crypto-c/target/build_linux64_wrappers
  - cmake -D CMAKE_INSTALL_PREFIX=/opt/amcl -D WORD_LENGTH=64 -D BUILD_PYTHON=on -D BUILD_GO=on -D GO_PATH=${GOPATH} -D BUILD_WCC=on ../..
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./
  - make
  - env CTEST_OUTPUT_ON_FAILURE=1 make test
  - echo -e "\n\n*** BUILD LINUX 64 ANONYMOUS ***\n\n"
  - mkdir -p /home/travis/build/miracl/milagro-crypto-c/target/build_linux64_anon
  - cd /home/travis/build/miracl/milagro-crypto-c/target/build_linux64_anon
  - cmake -D CMAKE_INSTALL_PREFIX=/opt/amcl -D WORD_LENGTH=64 -D USE_ANONYMOUS=on -D BUILD_WCC=on ../..
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./
  - make
  - env CTEST_OUTPUT_ON_FAILURE=1 make test
  - echo -e "\n\n*** BUILD LINUX 64 ***\n\n"
  - mkdir -p /home/travis/build/miracl/milagro-crypto-c/target/build_linux64
  - cd /home/travis/build/miracl/milagro-crypto-c/target/build_linux64
  - cmake -D CMAKE_INSTALL_PREFIX=/opt/amcl -D WORD_LENGTH=64 ../..
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./
  - make
  - env CTEST_OUTPUT_ON_FAILURE=1 make test
  - echo -e "\n\n*** BUILD LINUX 32 ***\n\n"
  - mkdir -p /home/travis/build/miracl/milagro-crypto-c/target/build_linux32
  - cd /home/travis/build/miracl/milagro-crypto-c/target/build_linux32
  - cmake -D CMAKE_INSTALL_PREFIX=/opt/amcl -D WORD_LENGTH=32 ../..
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./
  - make
  - env CTEST_OUTPUT_ON_FAILURE=1 make test
  - echo -e "\n\n*** BUILD WIN 64 ***\n\n"
  - mkdir -p /home/travis/build/miracl/milagro-crypto-c/target/build_win64
  - cd /home/travis/build/miracl/milagro-crypto-c/target/build_win64
  - cmake -D CMAKE_TOOLCHAIN_FILE=../../resources/cmake/mingw64-cross.cmake -D WORD_LENGTH=64 ../..
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./
  - make
  - env CTEST_OUTPUT_ON_FAILURE=1 make test
  - echo -e "\n\n*** BUILD WIN 32 ***\n\n"
  - mkdir -p /home/travis/build/miracl/milagro-crypto-c/target/build_win32
  - cd /home/travis/build/miracl/milagro-crypto-c/target/build_win32
  - cmake -D CMAKE_TOOLCHAIN_FILE=../../resources/cmake/mingw32-cross.cmake -D WORD_LENGTH=32 ../..
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./
  - make
  - env CTEST_OUTPUT_ON_FAILURE=1 make test

after_success:
  - coveralls-lcov /home/travis/build/miracl/milagro-crypto-c/target/build_test/coverage/amcl.info
